version: '3.8'

services:
  frontend:
    build: .
    container_name: habit-tracker-frontend
    ports:
      - "8080:8080"
    environment:
      - VITE_API_URL=http://91.142.72.17:7001/api/v1
    restart: unless-stopped
    network_mode: "host"
